name: Android Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y openjdk-21-jdk wget unzip neko

      - name: Install Haxe 4.2.5
        run: |
          wget https://github.com/HaxeFoundation/haxe/releases/download/4.2.5/haxe-4.2.5-linux64.tar.gz
          tar -xzf haxe-4.2.5-linux64.tar.gz
          mv haxe_* haxe
          sudo mv haxe /usr/local/
          echo "/usr/local/haxe" >> $GITHUB_PATH

      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v4.2.3
        with:
          key: cache-build-android
          path: |
            .haxelib/
            export/release/android/haxe/
            export/release/android/obj/

      - run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV

      - name: Run Codename Setup
        run: |
          haxe -cp commandline -D analyzer-optimize --run Main setup -s --no-vscheck
          haxelib run lime rebuild hxcpp

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK + NDK r25
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" \
                     "platforms;android-33" \
                     "build-tools;33.0.2" \
                     "ndk;25.2.9519653"

      - name: Set Android Environment
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

      - name: Lock OpenFL + Lime Versions
        run: |
         haxelib install hxvlc 1.9.3
         haxelib set hxvlc 1.9.3
         haxelib set lime git
         haxelib install openfl 9.2.2
         haxelib set openfl git

      - name: Lime Setup Android
        run: |
         printf "%s\n%s\n%s\n" \
         "$ANDROID_SDK_ROOT" \
         "$ANDROID_NDK_ROOT" \
         "$JAVA_HOME" \
         | haxelib run lime setup android

      - name: set hxcpp
        run: |
         haxelib set hxcpp git
         haxelib run lime rebuild hxcpp

      - name: Show Installed Libraries
        run: haxelib list

      - name: Build Android
        run: |
          haxelib run lime build android -final -clean

      - name: Find APKS 
        run: find . -name "*.apk"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android-Build
          path: export/release/android/bin/app/build/outputs/apk/debug/*.apk
